name: Test
on: push
jobs:
  super-lint:
    name: Test Aiven Monitor
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.1
      - name: Setup Dependencies
        run: |
          python3 -m venv venv
          venv/bin/pip install --upgrade pip setuptools wheel
          venv/bin/pip install --constraint constraints.txt .[speedups]
          venv/bin/pip install --editable .[speedups]
          venv/bin/pip install --upgrade --constraint constraints.txt --requirement docs/requirements.txt
          venv/bin/pip install --upgrade --constraint constraints.txt --requirement tests/requirements.txt
      - name: Run Tests
        run: |
          venv/bin/pytest --cov=.
          venv/bin/coverage html
          venv/bin/sphinx-build docs target/docs
          rm -rf target/.pytest_cache target/.coverage
      - name: Deploy Docs & Coverage
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target

