name: Test
on: push
jobs:
  super-lint:
    name: Test Aiven Monitor
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.1
      - name: Setup Dependencies
        run: |
          python3 -m venv venv
          venv/bin/pip install --upgrade pip setuptools wheel
          venv/bin/pip install --constraint constraints.txt .[speedups]
          venv/bin/pip install --editable .[speedups]
          venv/bin/pip install --upgrade --constraint constraints.txt --requirement docs/requirements.txt
          venv/bin/pip install --upgrade --constraint constraints.txt --requirement tests/requirements.txt
      - name: Configure Aiven Secrets
        env:
          KAFKA_CA_PEM: ${{ secrets.KAFKA_CA_PEM }}
          KAFKA_CERTIFICATE_PEM: ${{ secrets.KAFKA_CERTIFICATE_PEM }}
          KAFKA_PRIVATE_PEM: ${{ secrets.KAFKA_PRIVATE_PEM }}
          POSTGRES_CA_PEM: ${{ secrets.POSTGRES_CA_PEM }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        run: |
          echo "${KAFKA_CA_PEM}" > tests/github/kafka.ca.pem
          echo "${KAFKA_CERTIFICATE_PEM}" > tests/github/kafka.certificate.pem
          echo "${KAFKA_PRIVATE_PEM}" > tests/github/kafka.private.pem
          echo "${POSTGRES_CA_PEM}" > tests/github/postgres.ca.pem
          echo "${POSTGRES_PASSWORD}" > tests/github/postgres.password
      - name: Run Tests
        env:
          AIVEN_TEST_CHECKER_CONFIG_PATH: tests/github/checker.ini
          AIVEN_TEST_WRITER_CONFIG_PATH: tests/github/writer.ini
        run: |
          venv/bin/pytest
          venv/bin/coverage html
          venv/bin/sphinx-build -a docs target/docs
      - name: Deploy Docs & Coverage
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/docs

